### ISSUE TITLE
books server

### ISSUE THREAD

**Issue by djouamaah** [Eslamyounis34/KetabyStore#1]
where you can store your bdf books?

**Comment by Eslamyounis34** [comment]
Using firebase to store my pdf books for downloading,, And google drive for
reading online

**Comment by djouamaah** [comment]
thank you, i build your project to test it, but i think i need to build firebase database first

**Comment by Eslamyounis34** [comment]
If you want to have an access to my fire base data base give me your email
and i will add you to view my DB

**Comment by djouamaah** [comment]
okay thank you
my Email: djouamaah@gmail.com

**Comment by Eslamyounis34** [comment]
Okay i will add you tomorrow to Database users with view permission

**Comment by djouamaah** [comment]
thank you

**Comment by djouamaah** [comment]
for security reasons you must delete google service file

**Comment by djouamaah** [comment]
hello
don't forget to add me to view firebase db

**Comment by Eslamyounis34** [comment]
I am so sorry i completely forget to add you.. I will add you today.. And
please tell me if you facing any problem in app

**Comment by djouamaah** [comment]
okay
or you can just sent me a json backup file from firebase and i'll build my owne firebase db

**Comment by Eslamyounis34** [comment]
hello djouamaa .. i have already added you now as a viewer in DB ... tell
me if there is any problem

**Comment by Eslamyounis34** [comment]
Everything alright??

**Comment by djouamaah** [comment]
thank you i get the email 
thank you again if i need something i'll tell you

**Comment by Eslamyounis34** [comment]
You're welcome.. Test the app and tell me if there is any problem

**Comment by Eslamyounis34** [comment]
??

**Comment by djouamaah** [comment]
hello
Sorry I was busy last time
Everything is fine, if I find any problem I will inform you

**Comment by Eslamyounis34** [comment]
You are welcome

**Comment by djouamaah** [comment]
hello again
is posible to add admob ads to this app, and how if it posible?

**Comment by djouamaah** [comment]
@Eslamyounis34

**Comment by Eslamyounis34** [comment]
Hii,, what's up?

**Comment by djouamaah** [comment]
i migrat to androidX but when i build app-debug, the app stop without showing any think

**Comment by Eslamyounis34** [comment]
Did you build the app before correctly and run it?

**Comment by djouamaah** [comment]
@Eslamyounis34 are you there?

**Comment by djouamaah** [comment]
no i just learning how to build android app

**Comment by Eslamyounis34** [comment]
Yes

**Comment by djouamaah** [comment]
You whant to help me?

**Comment by Eslamyounis34** [comment]
Yes of course.

**Comment by djouamaah** [comment]
Thank you @Eslamyounis34 
I want to add admob to this app but i fail
